name: 编译TVBox-APK

on:
  workflow_dispatch:
    inputs:
      testOption:
        description: '打勾✅添加arm64支持不支持ijk解码'
        required: false
        type: boolean
      add_to_py:
        description: '打勾✅添加PY支持'
        required: false
        type: boolean
      source_branch:
        description: "选择TVBox源分支"
        required: false
        default: "q215613905"
        type: choice
        options:
          - q215613905
          - takagen99

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 ${{ inputs.source_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone project
        run: |
          git clone https://github.com/ne7359/tvbox.git diyTVBOX

      - name: diyTVBOX
        run: |
          cd diyTVBOX
          chmod +x TVBox/${{ inputs.source_branch }}/diy.sh
          source TVBox/${{ inputs.source_branch }}/diy.sh
          source ./config.sh
          cd TVBoxOSC
          echo PWD=$PWD >> $GITHUB_ENV

      - name: 测试选项
        if: ${{ inputs.testOption }}
        working-directory: $PWD
        run: |
          #添加arm64支持，不支持ijk解码
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" app/build.gradle
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" player/build.gradle
          cd

      - uses: gradle/gradle-build-action@v2

      - name: 使用 Gradle 构建
        working-directory: $PWD
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode alll

      - name: 添加编译时间
        working-directory: $PWD
        run: |
            echo "FILE_TIME=$(date "+%Y年%m月%d日-%H点%M分")" >> $GITHUB_ENV

      - name: 准备应用程序
        working-directory: $PWD
        run: |
          rm -rf apk/
          mkdir -p apk/
          for file in `find ~ -name "*release*.apk" -print`; do
            mv "$file" apk/QTMTv.apk
          done

      - name: 上传 APK 到 Release
        uses: ncipollo/release-action@main
        env:
           GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        with:
          name: QTM影视
          tag: ${{ env.FILE_TIME }}
          allowUpdates: true
          removeArtifacts: true
          body: |
            编译源：${{ inputs.source_branch }}
            🎈 编译时间：${{ env.FILE_TIME }}
            ⏰ 编译用时：${{ env.BUILD_TIME }}
          artifacts: |
            TVBoxOSC/apk/*.apk
