name: 编译TVBox-APK

on:
  workflow_dispatch:
    inputs:
      testOption:
        description: '打勾✅添加arm64支持不支持ijk解码'
        required: false
        type: boolean
      add_to_py:
        description: '打勾✅添加PY支持'
        required: false
        type: boolean
      source_branch:
        description: "选择TVBox源分支"
        required: false
        default: "q215613905"
        type: choice
        options:
          - q215613905
          - takagen99

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 ${{ inputs.source_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 获取 DIY 配置
        run: |
          git clone https://github.com/ne7359/tvbox.git diyTVBOX
          echo "FILE_TIME=$(date "+%Y年%m月%d日-%H点%M分")" >> $GITHUB_ENV   # 添加编译时间
          echo "BUILD_TIME=${HOUR}时${MIN}分${SEC}秒" >> $GITHUB_ENV         # 添加编译用时

      - name: DIY 源代码
        run: |
          cd diyTVBOX
          chmod +x TVBox/${{ inputs.source_branch }}/diy.sh
          source TVBox/${{ inputs.source_branch }}/diy.sh
          if [ -f "./TVBoxOSC/app/build.gradle" ]; then
            (
              source ./config.sh
            )
          fi 
          cd

      - name: 测试选项
        if: ${{ inputs.testOption }}
        working-directory: diyTVBOX/TVBoxOSC
        run: |
          #添加arm64支持，不支持ijk解码
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" app/build.gradle
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" player/build.gradle

      - name: 添加PY支持
        if: ${{ inputs.add_to_py }}
        working-directory: diyTVBOX/TVBoxOSC
        run: |
          echo '添加PY支持'
          wget --no-check-certificate -qO- "https://raw.githubusercontent.com/UndCover/PyramidStore/main/aar/pyramid-1011.aar" -O app/libs/pyramid.aar
          sed -i "/thunder.jar/a\    implementation files('libs@pyramid.aar')" app/build.gradle
          sed -i 's#@#\\#g' app/build.gradle
          sed -i 's#pyramid#\\pyramid#g' app/build.gradle
          echo "" >> app/proguard-rules.pro
          echo "" >> app/proguard-rules.pro
          echo "#添加PY支持" >> app/proguard-rules.pro
          echo "-keep public class com.undcover.freedom.pyramid.** { *; }" >> app/proguard-rules.pro
          echo "-dontwarn com.undcover.freedom.pyramid.**" >> app/proguard-rules.pro
          echo "-keep public class com.chaquo.python.** { *; }" >> app/proguard-rules.pro
          echo "-dontwarn com.chaquo.python.**" >> app/proguard-rules.pro
          sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/base/App.java
          sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/base/App.java
          sed -i '/PlayerHelper.init/a\        PythonLoader.getInstance().setApplication(this);' app/src/main/java/com/github/tvbox/osc/base/App.java
          sed -i '/import android.util.Base64;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
          sed -i '/import android.util.Base64;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
          sed -i '/private void parseJson(String apiUrl, String jsonStr)/a\        PythonLoader.getInstance().setConfig(jsonStr);' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
          sed -i '/public Spider getCSP(SourceBean sourceBean)/a\        if (sourceBean.getApi().startsWith(\"py_\")) {\n        try {\n            return PythonLoader.getInstance().getSpider(sourceBean.getKey(), sourceBean.getExt());\n        } catch (Exception e) {\n            e.printStackTrace();\n            return new SpiderNull();\n        }\n    }' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
          sed -i '/public Object\[\] proxyLoca/a\    try {\n        if(param.containsKey(\"api\")){\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"ck\"))\n                return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n            SourceBean sourceBean = ApiConfig.get().getSource(doStr);\n            return PythonLoader.getInstance().proxyLocal(sourceBean.getKey(),sourceBean.getExt(),param);\n        }else{\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"live\")) return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n        }\n    } catch (Exception e) {\n        e.printStackTrace();\n    }\n' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java

      - name: Setup JDK
        if: ${{ env.commit }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.javaVersion }}

      - name: 安装 Gradle
        uses: gradle/gradle-build-action@v3

      - name: 使用 Gradle 构建
        working-directory: diyTVBOX/TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all

      - name: 准备应用程序
        working-directory: diyTVBOX/TVBoxOSC
        run: |
          rm -rf apk/
          mkdir -p apk/
          for file in `find ~ -name "*release*.apk" -print`; do
            mv "$file" apk/QTM影视.apk
          done

      - name: 上传 APK 到 Release
        uses: ncipollo/release-action@main
        env:
           GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        with:
          name: QTM影视
          tag: ${{ env.FILE_TIME }}
          allowUpdates: true
          removeArtifacts: true
          body: |
            ★ 源码分支：${{ inputs.source_branch }}
            
            🎈 编译时间：${{ env.FILE_TIME }}
            
            ⏰ 编译用时：${{ env.BUILD_TIME }}

          artifacts: |
            diyTVBOX/TVBoxOSC/apk/*.apk
