name: 编译DiyTVBox

on:
  workflow_dispatch:
    inputs:
      android_arm64:
        description: '打勾✅添加arm64支持不支持ijk解码'
        required: false
        type: boolean
      android_x86:
        description: '打勾✅添加android for PC x86支持'
        required: false
        type: boolean
      add_py:
        description: '打勾✅添加PY支持'
        required: false
        type: boolean
      source_branch:
        description: "选择TVBox源分支"
        required: false
        default: "takagen99"
        type: choice
        options:
          - q215613905
          - takagen99
          - mlabalabala

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 ${{ inputs.source_branch }}

    steps:
      - name: 读取仓库文件
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 设置 DIY
        working-directory: ${{ github.workspace }}
        run: |
         chmod +x TVBox/${{ inputs.source_branch }}/diy.sh
         source TVBox/${{ inputs.source_branch }}/diy.sh

      - name: 拉取源并修改源代码
        working-directory: ${{ github.workspace }}
        run: |
          git clone -b main --depth=1 ${{ env.sourceURL }} TVBoxOSC
          chmod +x ./TVBoxOSC
          if [[ -f "./TVBoxOSC/app/build.gradle" && -f "./custom.sh" ]]; then
            chmod +x ./custom.sh
            ./custom.sh
          else
            echo "检查custom.sh文件不存在."
          fi

      #- name: 压缩 修改后的源代码
      #  working-directory: TVBoxOSC
      #  run: |
      #    tar -cJf DIYsource.tar.xz --exclude=.git --exclude=.github *

      - name: 添加 arm64-v8a 支持
        if: ${{ inputs.android_arm64 }}
        working-directory: ${{ github.workspace }}
        run: |
          source ./arm64-v8a.sh

      - name: 添加 x86 支持
        if: ${{ inputs.android_x86 }}
        working-directory: ${{ github.workspace }}
        run: |
          source ./add-X86.sh

      - name: 添加 PY 支持
        if: ${{ inputs.add_py }}
        working-directory: ${{ github.workspace }}
        run: |         
          source ./add-py.sh

      - name: 给软件签名
        working-directory: ${{ github.workspace }}
        run: |         
          source ./ApkSign.sh

      #- name: Setup JDK
      #  uses: actions/setup-java@v4
      #  with:
      #    distribution: temurin
      #    java-version: ${{ env.javaVersion }} #用于自定义版本，修改diy.sh 变量javaVersion=版本号
      - name: 检查JAVA版本 安装JDK
        working-directory: TVBoxOSC
        run: |
          setup_java_ver=$(grep -o 'JavaVersion.VERSION_[0-9_]\+' app/build.gradle |head -1 |sed 's/.*_//')
          if [ $setup_java_ver -gt 11 ]; then
            echo "setup_java_ver=$setup_java_ver" >> $GITHUB_ENV
          fi
      - uses: actions/setup-java@v4
        if: ${{ env.setup_java_ver }}
        with:
          distribution: temurin
          java-version: ${{ env.setup_java_ver }}

      - name: 安装 Gradle
        uses: gradle/gradle-build-action@v3

      - name: 使用 Gradle 构建
        working-directory: TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all

      - name: 准备应用程序
        working-directory: TVBoxOSC
        run: |
          rm -rf apk/
          mkdir -p apk/
          #for file in `find ~ -name "*release*.apk" -print`; do
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" apk/QTM-${{ env.sourceName }}.apk
            break
          done

      - name: 上传 APK 到 Release
        uses: ncipollo/release-action@main
        env:
           GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        with:
          name: QTM影视
          tag: ${{ env.tag }}
          allowUpdates: true
          removeArtifacts: true
          body: |
            ★ 源码分支：${{ inputs.source_branch }}
            
            🎈 编译时间：${{ env.tag }}

          artifacts: |
            TVBoxOSC/apk/*.apk
